### ISSUE TITLE
idea更新到2020.1版本不能用了

### ISSUE THREAD

**Issue by Forward233** [newhoo/quick-dev-intellij-plugin#2]

**Comment by Forward233** [comment]
只有一个Open Gitlab功能了，找不到其他的功能配置。
希望作者能更新一下，万分感谢。

**Comment by huzunrong** [comment]
不好意思，由于这个插件的几个功能依赖了jrebel，所以不再更新了，所有功能已经拆成了单独的插件。

**Comment by huzunrong** [comment]
不好意思，由于这个插件的几个功能依赖了jrebel，所以不再更新了，所有功能已经拆成了单独的插件。插件主页：

**Comment by newhoo** [comment]
你好，由于这个插件的几个功能依赖了jrebel，所以不再更新了。所有功能已经拆成了单独的插件，且不依赖jrebel。插件主页：https://plugins.jetbrains.com/author/6c08090c-6cc3-4b01-94a2-2c9a9947b6cd

- 快速打开配置中心 https://plugins.jetbrains.com/plugin/13202-apollo-conf

- MySQL EXPLAIN https://plugins.jetbrains.com/plugin/13192-mysql-explain

- 快速调用 https://plugins.jetbrains.com/plugin/13203-bean-invoker

- jvm启动参数管理 https://plugins.jetbrains.com/plugin/13204-jvm-parameter

- 快速打开git仓库 暂时没上传，给你找了个https://plugins.jetbrains.com/plugin/8183-gitlink
